var propuestas = null
function CargarPropuestas()
{
propuestas = [
//Horacio R. Larreta
Propuesta("Acompañar el crecimiento de los chicos desde el embarazo hasta los primeros años de vida", "Para generar más oportunidades en la Ciudad, tenemos que empezar por ELLOS. Lo que no reciben en sus primeros meses de vida, ya sea falta de estímulos, alimentos o amor, no lo recuperan más. Vamos a ampliar el programa “Primeros Meses” que garantiza asistencia médica y ayuda económica para las madres en situaciones de vulnerabilidad. Además, nos comprometemos a llegar a los 100 Centros de Primera Infancia. Ellos van a seguir siendo nuestra prioridad. No desde las palabras, sino desde la acción, con cambios que realmente mejoren su calidad de vida.", temas.SOCIEDAD, 1, 0),
Propuesta("Más skateparks en los barrios", "Uno de nuestros principales objetivos es devolverles a todos los vecinos un espacio público verde y limpio para que puedan disfrutar de hacer deporte. Nosotros nos comprometemos a seguir promoviendo las actividades al aire libre y construir más skateparks en la Ciudad. Además, está ligado a una vida sana, genera compromiso y pasión. Es mucho más que un talento, es una actitud que te ayuda a ir para adelante.", temas.PLANEAMIENTO_URBANO, 1, 0),
Propuesta("WiFi en toda la Ciudad", "Nuestro compromiso es que desde cualquier lugar de la Ciudad los vecinos puedan acceder a Internet de manera gratuita para promover la inclusión digital y potenciar las capacidades creativas, productivas y de ocio que Internet ofrece. Hablar de innovación es buscar soluciones a los problemas comunes de la gente.", temas.PLANEAMIENTO_URBANO, 1, 0),
Propuesta("Metrobus Transversal", "Iría de sur a norte. Bajaría el tiempo de viaje a más de la mitad, siendo la primera línea eléctrica de colectivos, lo que reduce el impacto ambiental y aporta mayor seguridad vial. El transporte público es una prioridad y apostamos a que cada vez sean más personas las que lo elijan. Una Ciudad más conectada es una Ciudad con mayor inclusión.", temas.TRANSPORTE, 1, 0),
Propuesta("Disminuir la obesidad infantil", "En la niñez aprendemos hábitos que adoptamos a lo largo de nuestra vida. Más del 40% de los chicos en edad escolar tienen sobrepeso y ante esta problemática creamos programas como las Jugotecas, Mi Escuela Saludable y Recreo en Movimiento. Rigen en el 22% de las escuelas de gestión estatal: nuestra meta es llegar al 100%. Mi propuesta es concientizar sobre la importancia de una dieta sana y equilibrada para disminuir el avance del sobrepeso y cuidar la salud.", temas.SALUD, 1, 0),

//Gabriela Michetti
Propuesta("Metrobus", "Nuevo Metrobus Norte Sur por Libertador–Alem–Paseo Colón. Finalizar Metrobus en la Autopista 25 de Mayo.", temas.TRANSPORTE, 1, 1),
Propuesta("Extensión de la Línea E", "Extensión de la Línea E hasta la nueva terminal de ómnibus", temas.TRANSPORTE, 1, 1),
Propuesta("Construcción de nuevos subtes", "Construcción de las nuevas Líneas G(Retiro hasta el Cid Campeador) y F(Entre Ríos–Callao) de subterraneo", temas.TRANSPORTE, 1, 1),
Propuesta("Autopista Ribereña: Ordenar el tránsito de camiones", "", temas.TRANSPORTE, 1, 1),
Propuesta("Urbanización de terrenos de Libertador al río", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Plan integral de recuperación del espacio público en el barrio de Constitución", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Remodelación del entorno de la Estación Constitución", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Impulsar áreas de prioridad peatón", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("3 nuevos espacios verdes en la Comuna 1", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Se plantarán 36.000 nuevos árboles en la Comuna 1", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Realización del Parque del Bicentenario (entre el Correo y Belgrano)", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Nueva estación de trasbordo de Retiro Norte detrás de la Facultad de Derecho, en conjunto con el Poder Ejecutivo Nacional", "", temas.TRANSPORTE, 1, 1),
Propuesta("Duplicar la frecuencia de los subtes", "", temas.TRANSPORTE, 1, 1),
Propuesta("Integrar los espacios bajo la Autopista 25 de Mayo a la trama urbana", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Ordenamiento integral del comercio en el barrio de San Telmo", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Recuperar el tranvía de Puerto Madero conectándolo con la Boca y Retiro", "", temas.TRANSPORTE, 1, 1),
Propuesta("Plan integral de recuperación urbana del área del Congreso Nacional", "", temas.TRANSPORTE, 1, 1),
Propuesta("Programas sociales para personas en situación de calle", "", temas.SOCIEDAD, 1, 1),
Propuesta("Mejorar el nodo Obelisco como centro de transferencia Metropolitana", "", temas.TRANSPORTE, 1, 1),
Propuesta("Red de corredores verdes", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Puesta en valor de los teatros General San Martin y Presidente Alvear", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Puesta en valor de plazas barriales en la Comuna 1", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Mejoramiento integral de la Plaza San Martín", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Nuevos usos urbanos para los terrenos portuarios actualmente en desuso", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Mejorar el ordenamiento del tránsito en el área central", "", temas.TRANSPORTE, 1, 1),
Propuesta("Mejorar accesibilidad a la Reserva Ecológica", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Finalizar el Parque y Centro de Exposiciones y Convenciones", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Mejorar el sistema de residuos", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Mejorar las condiciones de la zona de facultades en la Comuna 2", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("2 nuevos espacios verdes en la Comuna 2", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Se plantarán 9.500 nuevos árboles en la Comuna 2", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Recuperar la relación con el río. Plan integral de acceso público al frente costero", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Reordenamiento de la circulación de colectivos hacia avenidas", "", temas.TRANSPORTE, 1, 1),
Propuesta("Extensión de la Línea H", "", temas.TRANSPORTE, 1, 1),
Propuesta("Plan Hidraúlico", "Cuenca del arroyo Ugarteche: Resolver anegamientos sobre la calle Austria. Sistema de alerta temprana para prevenir inundaciones. Completar la red secundaria de las cuencas de los arroyos Erezcano, Ochoa-Elia, Boca-Barracas.", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Regular el estacionamiento de vehículos en la vía pública", "", temas.TRANSPORTE, 1, 1),
Propuesta("Programa de protección patrimonial", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Regulación de publicidad y contaminación visual", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Mejoramiento integral de veredas", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Plan integral de recuperación urbanística del Abasto", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Plan integral de recuperación urbanística del entorno Mercado Spinetto", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Restauración Plaza Miserere", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Plaza homenaje a las víctimas de Cromañón", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Programa de terrazas verdes", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Fortalecer los centros comerciales a cielo abierto: Entre Ríos, Callao, Belgrano, Pueyrredón, San Juan", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Redes barriales de ciclovías", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Nuevas sedes de Gobierno en el Sur", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Nuevo Centro de Trasbordo Sáenz", "", temas.TRANSPORTE, 1, 1),
Propuesta("Elevación del Ferrocarril Belgrano Sur", "Elevación del Ferrocarril Belgrano Sur en conjunto con el Poder Ejecutivo Nacional, conectando con Estación Constitución.", temas.TRANSPORTE, 1, 1),
Propuesta("Mejoramiento integral del entorno de la Usina del Arte", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Urbanización de la Villa 21-24", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Programa de mejora habitacional en la Boca", "", temas.PLANEAMIENTO_URBANO, 1, 1),
Propuesta("Nuevos puentes sobre el Riachuelo", "Nuevos puentes sobre el Riachuelo: Roca – Patricios, Pedriel. Puentes peatonales. Recuperación de los puentes viejos", temas.TRANSPORTE, 1, 1),
Propuesta("Nueva terminal de ómnibus sur", "", temas.TRANSPORTE, 1, 1),

//Martin Lousteau
Propuesta("Sanciones a las empresas de basura", "Controlar y penalizar a las empresas de recolección que no cumplan con sus obligaciones.", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Profesionalizar a las cooperativas de recicladores urbanos", "", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Cumplir la ley de basura cero", "", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Reducir residuos no renovables", "Reducir los residuos no renovables mediante incentivos impositivos y normativas especiales.", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Capacitar e incentivar a separar los residuos en cada casa", "", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Recolección diferenciada", "Establecer de forma obligatoria la recolección diferenciada de residuos.", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Transformar los Centros de Primera Infancia en jardines de infantes educativos", "", temas.EDUCACION, 2, 0),
Propuesta("Aumentar inversión educativa", "", temas.EDUCACION, 2, 0),
Propuesta("Jerarquizar la formación docente, articular con la UBA", "", temas.EDUCACION, 2, 0),
Propuesta("Crear un legajo único por alumno", "", temas.EDUCACION, 2, 0),
Propuesta("Extender jornadas ecolares de escuelas estatales", "", temas.EDUCACION, 2, 0),
Propuesta("Sancionar Ley de Educación para la CABA", "", temas.EDUCACION, 2, 0),
Propuesta("No vamos a reducir un m2 más de los espacios verdes de la CABA", "", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Cuida-Coches", "Regular la actividad de cuida-coches con registro y tarifa única como en Uruguay.", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Venta en la vía pública", "Regular la venta legal en la vía pública creando espacios especiales para la venta.", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Reparación de baches y veredas", "Transferencia de presupuesto a las Comunas para la reparación de baches y veredas. Sistema digital para denuncia y seguimiento de obras de veredas y baches.", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Centros de Atención Primaria", "Equipar los centros de atención primaria y dotarlos de un equipo médico interdiciplinario.", temas.SALUD, 2, 0),
Propuesta("Crear un polo de alta complejidad por región sanitaria", "", temas.SALUD, 2, 0),
Propuesta("Programas Médico de cabecera y pedriatra en casa", "", temas.SALUD, 2, 0),
Propuesta("Sistema de derivación para emergencias y regionalización de la salud neonatal", "", temas.SALUD, 2, 0),
Propuesta("Tarjeta de salud con historia clínica digitalizada", "", temas.SALUD, 2, 0),
Propuesta("Insistir en el traspaso de la Policía Federal con sus recursos", "", temas.SEGURIDAD, 2, 0),
Propuesta("Presencia de la Policía Metropolitana en más comunas", "", temas.SEGURIDAD, 2, 0),
Propuesta("Sistema descentralizado de denuncias, información y estadística criminal", "", temas.SEGURIDAD, 2, 0),
Propuesta("Más control y sanciones en las zonas comerciales que venden productos robados", "", temas.SEGURIDAD, 2, 0),
Propuesta("Metrobús", "Desarrollar el verdadero potencial del metrobús: unidades articuladas exclusivas y de amplia capacidad.", temas.TRANSPORTE, 2, 0),
Propuesta("Normas de Tránsito", "Hacer respetar las normas de ordenamiento de tránsito, carga y descarga, doble fila y horario de circulación de camiones.", temas.TRANSPORTE, 2, 0),
Propuesta("Crear la autopista ribereña subterránea", "", temas.TRANSPORTE, 2, 0),
Propuesta("Subte", "Construir la Linea F de subte entre Constitución y Plaza Italia.", temas.TRANSPORTE, 2, 0),
Propuesta("Prohibición de la utilización de la publicdad oficial como propaganda política", "", temas.SOCIEDAD, 2, 0),
Propuesta("Sistema para solicitar información pública en formato abierto y accesible", "", temas.SOCIEDAD, 2, 0),
Propuesta("Incentivos y protección para los denunciantes de corrupción", "", temas.SOCIEDAD, 2, 0),
Propuesta("Modificación de las normas para reducir la discrecionalidad en las compras y contrataciones", "", temas.SOCIEDAD, 2, 0),
Propuesta("Presupuesto", "Aumentar y ejecutar la totalidad del presupuesto destinado a vivienda.", temas.PLANEAMIENTO_URBANO, 2, 0),
Propuesta("Préstamos", "Subsidiar la tasa de interés para entregar 3800 préstamos al año con una tasa de un dígito. Reducir a la mitad el ingreso requerido para acceder al préstamo privilegiando la primera casa.", temas.ECONOMIA, 2, 0),
Propuesta("Urbanización", "Priorizar la integración en la urbanización duplicando la participación del gasto en vivienda.", temas.PLANEAMIENTO_URBANO, 2, 0),

//Graciela Ocaña
Propuesta("Instalación de cámaras de seguridad en todas las comunas", "", temas.SEGURIDAD, 2, 1),
Propuesta("Tendido de redes de fibra óptica para control online de cámaras", "", temas.SEGURIDAD, 2, 1),
Propuesta("Instalación de Centros de Monitoréo Barriales", "", temas.SEGURIDAD, 2, 1),
Propuesta("Policía Metropolitana", "Policía Metropolitana en todas las comunas con el traspaso del personal de la Policía Federal.", temas.SEGURIDAD, 2, 1),
Propuesta("Ubicación de garitas", "Ubicación de garitas barriales con radio de acción o cuadrículas claramente delimitadas y conectadas al centro de monitoréo.", temas.SEGURIDAD, 2, 1),
Propuesta("Entrega de botón anti pánico con central de monitoreo para taxis", "", temas.SEGURIDAD, 2, 1),
Propuesta("Prohibición de cobros en la vía pública (Trapitos)", "", temas.SEGURIDAD, 2, 1),
Propuesta("Gestión hospitalaria", "Nuevo modelo de gestión hospitalaria con atención ampliada de 07 a 20 hs.", temas.SALUD, 2, 1),
Propuesta("Mejoras edilicias.", "", temas.SALUD, 2, 1),
Propuesta("Modernización de instalaciones", "", temas.SALUD, 2, 1),
Propuesta("Historia clínica online", "", temas.SALUD, 2, 1),
Propuesta("Tarjeta biométrica", "", temas.SALUD, 2, 1),
Propuesta("Sistema único de ambulancias para la Ciudad", "", temas.SALUD, 2, 1),
Propuesta("Servicios de gerontología", "", temas.SALUD, 2, 1),
Propuesta("Creación de centros para la prevención y tratamiento de adicciones y ludopatía", "", temas.SALUD, 2, 1),
Propuesta("Creación de centros de noche y centros intermedios para la rehabilitación de las adicciones", "", temas.SALUD, 2, 1),
Propuesta("Entrega de botones antipánico para todos los jubilados de la Ciudad", "", temas.SEGURIDAD, 2, 1),
Propuesta("Fondo de adelantamiento para el pago de las sentencias ANSES por reajuste de haberes", "", temas.SOCIEDAD, 2, 1),
Propuesta("Hipoteca inversa: adelanto de dinero mensual con garantía hipotecaria", "", temas.ECONOMIA, 2, 1),
Propuesta("Unidad de coordinación de políticas de la tercera edad ", "Creación de una Unidad de coordinación de políticas de la tercera edad (PAMI - ANSES - Salud - Recreación - Cultura).", temas.SOCIEDAD, 2, 1),
Propuesta("Boleto Educativo", "Boleto Educativo gratuito para alumnos, personal docente y no docente de los establecimientos educativos públicos y privados.", temas.EDUCACION, 2, 1),
Propuesta("Jardines Maternales", "Ampliación de la oferta de jardines maternales para niños de 2 a 3 años.", temas.EDUCACION, 2, 1),
Propuesta("Doble escolaridad para todas las escuelas públicas de la Ciudad", "", temas.EDUCACION, 2, 1),
Propuesta("Programa para la prevención por el uso de estupefacientes en la escuela secundaria", "", temas.EDUCACION, 2, 1),
Propuesta("Seguimiento especializado de la deserción escolar", "", temas.EDUCACION, 2, 1),
Propuesta("Plan de sanidad escolar", "", temas.EDUCACION, 2, 1),
Propuesta("Tarifa integrada para medios de transporte", "", temas.TRANSPORTE, 2, 1),
Propuesta("Metrobús", "Metrobús no como carril exclusivo sino como sistema integrado de transporte.", temas.TRANSPORTE, 2, 1),
Propuesta("Transparencia en la gestión pública", "", temas.INSTITUCIONAL, 2, 1),
Propuesta("Compras y licitaciones", "Nuevo modelo de compras y licitaciones que amplíen la ofertas, disminuyendo los costos de los servicios para la Ciudad.", temas.INSTITUCIONAL, 2, 1),
Propuesta("Ley anti corrupción de la Ciudad", "", temas.INSTITUCIONAL, 2, 1),
Propuesta("Fortalecimiento de la Auditoria General de la Ciudad", "", temas.INSTITUCIONAL, 2, 1),
Propuesta("Funcionamiento pleno de las Comunas, descentralizando fondos y decisiones", "", temas.INSTITUCIONAL, 2, 1),
Propuesta("Recuperación de competencias en materia de Policía, Justicia, Juego y Puertos", "", temas.INSTITUCIONAL, 2, 1),
Propuesta("Plan de urbanización de las villas de emergencia de la Ciudad", "", temas.PLANEAMIENTO_URBANO, 2, 1),
Propuesta("Creación de una línea de créditos para familias jóvenes", "", temas.ECONOMIA, 2, 1),
Propuesta("Sistema de Garantías", "Modernización del sistema de garantías, reemplazando la garantía propietaria por el seguro de caución.", temas.SOCIEDAD, 2, 1),
Propuesta("Instituto de la Vivienda de la Ciudad", "Gestión transparente y eficiente de los recursos del Instituto de la Vivienda de la Ciudad.", temas.SOCIEDAD, 2, 1),
Propuesta("Recuperación de los fondos judiciales del Banco Ciudad para el otorgamiento de créditos", "", temas.ECONOMIA, 2, 1),
Propuesta("Cumplimiento de la ley de Basura Cero", "", temas.PLANEAMIENTO_URBANO, 2, 1),
Propuesta("Programa para la concientización de la separación en origen", "", temas.PLANEAMIENTO_URBANO, 2, 1),
Propuesta("ABL", "Reducción del ABL para vecinos que adhieran al Programa Hogares Verdes, separando la basura en el hogar.", temas.PLANEAMIENTO_URBANO, 2, 1),
Propuesta("Creación del programa de vecinos veedores voluntarios", "", temas.PLANEAMIENTO_URBANO, 2, 1),
Propuesta("Programa de incentivo de empleo para jóvenes de 18 a 30 años", "", temas.SOCIEDAD, 2, 1),
Propuesta("Alquiler de Jóvenes", "Programa para facilitar el alquiler de jóvenes a fin de poder iniciar su carrera profesional.", temas.SOCIEDAD, 2, 1),
Propuesta("Educación Sexual", "Creación de consultorías de educación sexual en escuelas, centros de salud y en todos los eventos vinculados a los jóvenes que organiza la Ciudad.", temas.EDUCACION, 2, 1),
Propuesta("Creación de la LINEA de denuncia de Drogas", "", temas.SEGURIDAD, 2, 1),
Propuesta("Ciudad como querellante en causas de narcotráfico", "", temas.SEGURIDAD, 2, 1),

//Andrés Borthagay
Propuesta("Prioridad al transporte público, al peatón y a la bicicleta", "", temas.TRANSPORTE, 2, 2),
Propuesta("Frecuencia, seguridad y calidad en transporte público", "", temas.TRANSPORTE, 2, 2),
Propuesta("Jerarquización de la red ferroviaria y fluvial", "Alivio de la red vial, que además de ser cara e insuficiente, está por completo saturada.", temas.TRANSPORTE, 2, 2),
Propuesta("Prioridad a los siguientes medios:", "Ferrocarril y subte como columna vertebral; el metrobús como sistema de capacidad intermedia; colectivos como sistema capilar.", temas.TRANSPORTE, 2, 2),
Propuesta("Plan de inversión a nivel metropolitano (tren/ subte)", "Financiamiento a partir de los fondos recaudados por los peajes de autopista, entre otros.", temas.TRANSPORTE, 2, 2),
Propuesta("Medidas de emergencia y medidas estructurales para evitar riesgos y recuperar el sistema en su conjunto", "", temas.TRANSPORTE, 2, 2),
Propuesta("Mejora del sistema Sube y los sistemas de información", "", temas.TRANSPORTE, 2, 2),
Propuesta("Seguridad víal:", "visión cero de la mortalidad de peatones. Límite máximo de velocidad: 50 km por hora.", temas.TRANSPORTE, 2, 2),
Propuesta("Política de estacionamiento", "Al servicio del ordenamiento del tránsito y no de concesionarios y concedentes circunstanciales.", temas.TRANSPORTE, 2, 2),
Propuesta("Preservación de las plazas como plazas y no como macetas ornamentales que coronan estacionamientos.", "", temas.TRANSPORTE, 2, 2),
Propuesta("Sistemas más avanzados tecnológicamente, en plazos flexibles y razonables", "En lugar de las concesiones actuales de autopistas y las proyectadas de estacionamiento.", temas.TRANSPORTE, 2, 2),
Propuesta("Mejora de estaciones", "Centros de transferencia (tren, subte, colectivos, bicicleta) y paradas.", temas.TRANSPORTE, 2, 2),
Propuesta("Desarrollo del actual sistema de bicicletas", "Proyectado a toda la ciudad. Sistemática pedagogía de las indispensables normas de  convivencia que esto implica.", temas.TRANSPORTE, 2, 2),
Propuesta("Programación de cruces callejeros con tiempos adecuados y seguros para la circulación de adultos mayores y chicos.", "", temas.TRANSPORTE, 2, 2),
Propuesta("Códigos de planeamiento sin ambigüedades ni superposición normativa. Hoy conviven dos “códigos”. Marco legal a favor del crecimiento sustentable y no a la especulación.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Vivienda social como parte global de la estrategia de desarrollo.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Hábitat: derecho a una vivienda digna que no sea inalcanzable para la mayoría.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Utilizar las regulaciones edilicias y los terrenos disponibles para potenciar la vivienda social.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Políticas crediticias concretas que faciliten el acceso a la primera vivienda.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Promoción de las cooperativas de vivienda.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Plan de financiamiento de vivienda, incluidas propuestas específicas para la población más joven y la clase media.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Utilización eficaz de los recursos de la ciudad, en cada una de las redes de infraestructura, incluyendo un plan energético.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Incentivo y realización de campañas para concientizar sobre el consumo racional. Ejemplos: balance térmico en las nuevas  construcciones, comisión de estándares en consumo energético de electrodomésticos", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Implementación de un sistema de consulta a la sociedad y a los profesionales que permita mejorar la calidad y la legitimidad de las propuestas.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Abordaje de los problemas de seguridad del Aeroparque sin conflictos de interés con el concesionario de la operación, 2respetando el medio ambiente y el patrimonio urbano.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Participación de la Ciudad en la gestión del puerto – eslabón clave en la cadena logística - con una verdadera articulación  puerto-ciudad, en el marco de un sistema de puertos metropolitanos y de una integración racional de las conexiones terrestres.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Desarrollo del puerto de cruceros con un sistema de conexión en la ciudad. ", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("No avalar desde la Ciudad concesiones portuarias de largo plazo que perjudiquen sus intereses. (entre ellas la que está en proceso a treinta años).", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("La ciudad debe tener una base de 500.000 árboles bien distribuidos (el censo de 2011 contabiliza 372.000) en la ciudad.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Revisión de contratos de limpieza, a la luz del alto costo y las deficiencias del actual sistema. ", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Campaña pedagógica de promoción de hábitos para una gestión sustentable de los residuos. ", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Actualización normativa de embalaje, basura electrónica.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Articulación de un sistema de flujos metropolitanos. Revisión delavance en centros de tratamiento de residuos sobre rellenos  costeros.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Respeto y continuidad a un plan de manejo y de gestión de la rivera.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Control de los niveles de ruido, que actualmente superan los estándares internacionales.", "", temas.PLANEAMIENTO_URBANO, 2, 2),Propuesta("Cotejo de los niveles de emisión con los establecidos en el plan energético.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Plan integral de gestión del agua por cuenca hídrica.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Ejecución de las grandes infraestructuras pendientes en materia de inundaciones, medidas estructurales y no estructurales.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Finalización de los rellenos en la costa del río y la impermeabilización del suelo como primera medida anti-nundaciones. Publicación de cotas de inundación.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Continuidad del PPI. ", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Impulso a la innovación y la incorporación de tecnologías sustentables (no solo desde el punto de vista ambiental).", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Apoyo al desarrollo emprendedor y la empleabilidad.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Diseño (participativo) y desarrollo de una estrategia económico/productivo/laboral para cada comuna o macrocomuna (dos o tres comunas vecinas), que incorpore a empresarios, emprendedores, profesionales, comerciantes, vecinos, ONGs, sistema educativo, etc.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Evaluación ambiental estratégica.", "", temas.PLANEAMIENTO_URBANO, 2, 2),
Propuesta("Visión estratégica de la educación", "Que dé sentido y direccionalidad al conjunto de las acciones. Flexibilización del diseño curricular, con pautas propias de la ciudad. ", temas.EDUCACION, 2, 2),
Propuesta("Aumento de recursos", "Tanto a nivel nacional como de la ciudad, el aumento de recursos es condición necesaria pero no suficiente para mejorar el nivel educativo. En lo edilicio, como en lo tecnológico y lo salarial. Debe ser sostenida pero acompañada de medidas sustantivas en lo educativo.", temas.EDUCACION, 2, 2),
Propuesta("Jerarquización docente", "Becas de formación docente para los mejores promedios. Política de jerarquización del docente frente a curso, para que los mejores maestros estén al frente del aula y no en funciones de otra índole. ", temas.EDUCACION, 2, 2),
Propuesta("Política sistemática de equipamiento y provisión de recursos", "A los maestros, docentes y profesores, principal apoyo para liberar las habilidades y capacidades de los alumnos.", temas.EDUCACION, 2, 2),
Propuesta("Plan de mejora por escuela", "Consensuada con directivos y docentes, con un análisis del entorno de los alumnos. Jerarquización de estas perspectivas con respecto a intereses particulares y corporativos.", temas.EDUCACION, 2, 2),
Propuesta("Reemplazo del actual sistema de excepciones sistemáticas", "Por una carrera docente basada en reglas de evolución claras. Asignación de puntajes basada en un sistema confiable.", temas.EDUCACION, 2, 2),
Propuesta("Desarrollo del sistema de investigación de la ciudad", "Creación deInstitutos en relación con la red de universidades existentes. Articular conocimiento y desarrollo económico.", temas.EDUCACION, 2, 2),
Propuesta("Asignación geográfica de inversiones", "Y localización de actividades como camino hacia la reversión de la inadmisible desigualdad educativa y de oportunidades entre las comunas de la ciudad: inversiones específicas, localización de actividades, etc.", temas.SOCIEDAD, 2, 2),
Propuesta("Políticas de igualdad de género:", "Gabinete social y plan de igualdad de oportunidades que comprenda a todos las áreas de gobierno. ", temas.SOCIEDAD, 2, 2),
Propuesta("Políticas para los jóvenes:", "Mayor desarrollo deportivo barrial, integración e inclusión en proyectos educativos, informáticos y  productivos que les posibiliten mejores oportunidades laborales.", temas.SOCIEDAD, 2, 2),
Propuesta("Violencia contra la mujer", "Políticas activas para prevenir y erradicar la violencia contra la mujer y todo tipo de violencia y discriminación institucional que se funde en los valores de la solidaridad y convivencia democrática.", temas.SOCIEDAD, 2, 2),
Propuesta("Inclusión de los adultos mayores:", "Como ciudadanos activos la ciudad debe valorar su potencial e integrarlos como sujetos y no como meros espectadores. Adaptación de infraestructuras, complemento de planes de salud, oferta urbana en general.", temas.SOCIEDAD, 2, 2),
Propuesta("Salud:", "Acceso a la atención primaria en los centros de salud. Creación y equipamiento comenzando con las comunas más postergadas del sur de la ciudad con alarmantes índices de mortalidad infantil y materna. Promoción, prevención y asistencia primaria de la salud sin demoras. Consejerías en salud sexual y reproductiva y prevención del embarazo adolescente.", temas.SALUD, 2, 2),
Propuesta("Desarrollo de estrategia orientada a la creación de una marca ciudad.", "", temas.SOCIEDAD, 2, 2),
Propuesta("Comunas e integración metropolitana son dos caras de una moneda", "Una ciudad policéntrica, con un programa integrado de Centros cívicos en los barrios, concebidos como tales, y no uno que concentre toda la administración en un lugar.", temas.INSTITUCIONAL, 2, 2), 
Propuesta("Un sistema modelo de empresas públicas", "Que funcionen y respondan a la ley puede potenciar el desarrollo de los recursos en Buenos Aires. Parte del sistema actual representa lo peor de los dos mundos: fondos públicos y discrecionalidad en el manejo.", temas.INSTITUCIONAL, 2, 2),
Propuesta("Agenda anti corrupción:","Control de licitaciones desde la fijación de precios base, hacer del acceso a la información un pilar de la modernización, publicación de agendas, fortalecimiento de los organismos de control.", temas.INSTITUCIONAL, 2, 2),
Propuesta("Respetar las leyes de empleo público y la profesionalización dela administración.", "", temas.INSTITUCIONAL, 2, 2),
Propuesta("Leyes de partidos y electoral de la ciudad", "Que permitan un cambio completo del sistema político tradicional, junto a comunas jerarquizadas y con todas las competencias.", temas.INSTITUCIONAL, 2, 2),
Propuesta("Hacer de la coordinación de las fuerzas de policía una oportunidad de reforma y modernización.", "", temas.INSTITUCIONAL, 2, 2),
Propuesta("Facilitar el acceso a la justicia, desburocratizar el funcionamientoen el desarrollo de la jurisdicción local.", "", temas.INSTITUCIONAL, 2, 2),
Propuesta("Articulación con una política federal contra la droga y el narcotráfico.", "", temas.INSTITUCIONAL, 2, 2),
Propuesta("Potenciar los programas de probation", "", temas.INSTITUCIONAL, 2, 2),
Propuesta("Cambio cultural", "Como en Bogotá, para tratar la violencia. La ciudad no se transforma exclusivamente desde el Gobierno, sino también desde las actitudes de los ciudadanos. Algunas medidas: la promoción de formas no violentas de manifestación, otro tipo de festejos de fin de año, una cultura del fútbol más festiva y menos violenta, etc.", temas.INSTITUCIONAL, 2, 2),

//Myriam Bregman
Propuesta('Salario mínimo igual al costo de la canasta familiar','Salario mínimo igual al costo de la canasta familiar indexado periódicamente según el aumento real del costo de vida. Derogación del impuesto al salario. Asignaciones familiares para todos',temas.ECONOMIA, 9,0),
Propuesta('Reestablecimiento del 82% móvil','Reestablecimiento del 82% móvil. Pago de las retroactividades correspondientes. Que la ANSES esté bajo la administración directa de jubilados y trabajadores.',temas.ECONOMIA, 9,0),
Propuesta('Reparto de las horas de trabajo con igual salario','Reparto de las horas de trabajo con igual salario para terminar con la desocupación. Prohibición de despidos y suspensiones.',temas.ECONOMIA, 9,0),
Propuesta('Basta de tercerización','Basta de tercerización. Todos a planta permanente, con vigencia del convenio más favorable. Abajo las leyes flexibilizadoras.',temas.ECONOMIA, 9,0),
Propuesta('Basta de espionaje a los luchadores','Basta de espionaje a los luchadores, que se haga pública la base de datos de “Proyecto X” y que se entregue la información a quienes fueron espiados. Basta de infiltración de las organizaciones populares. Cese de la persecución y anulación de las causas judiciales contra los más de 5.000 luchadores obreros y populares. Absolución de los trabajadores de Las Heras.',temas.SOCIEDAD, 9,0),
Propuesta('Expropiación definitiva sin pago de Zanón','Expropiación definitiva sin pago de Zanón y demás fábricas recuperadas.',temas.ECONOMIA, 9,0),
Propuesta('No al pago de la deuda externa','No al pago de la deuda externa. Recursos para salarios, trabajo, salud, educación y vivienda, no para la deuda. ',temas.ECONOMIA, 9,0),
Propuesta('Reestatización de todas las privatizadas','Reestatización de todas las privatizadas bajo control administración y gestión de trabajadores y usuarios. Reestatización de todo el sistema ferroviario bajo control, administración y gestión de los trabajadores de todos los niveles y usuarios.',temas.ECONOMIA, 9,0),
Propuesta('Renacionalización del 100% de YPF y todas las empresas petroleras','Renacionalización del 100% de YPF y todas las empresas petroleras: por una empresa nacional estatal única que funcione bajo el control y la gestión de sus trabajadores. Por un plan nacional energético controlado por los trabajadores. Nacionalización -sin indemnización y bajo administración y control de trabajadores-, de la banca y el comercio exterior, la minería y el gran capital agrario e industrial. Por un plan económico debatido y gestionado por los trabajadores. ',temas.ECONOMIA, 9,0),
Propuesta('Por la expropiación de la oligarquía terrateniente','Por la expropiación de la oligarquía terrateniente, de los grandes pools de siembra, así como de los monopolios cerealeros, aceiteros y frigoríficos. Por la nacionalización de la tierra, comenzando con la expropiación de los 4000 principales propietarios, respetando los derechos de los campesinos pobres, pueblos originarios y pequeños chacareros que no exploten mano de obra asalariada”. No a la expulsión de sus tierras de campesinos y originarios. Juicio y castigo a los responsables de los asesinatos de los QOM de Formosa, y plena satisfacción a los reclamos. Basta de trabajo en negro para los trabajadores rurales. ',temas.ECONOMIA, 9,0),
Propuesta('Defensa de la educación y salud públicas y gratuitas','Defensa de la educación y salud públicas y gratuitas. Basta de subsidio a la educación privada. Fuera la iglesia de la educación. Abajo la Ley de Educación Superior. Que el Estado deje de financiar a la Iglesia Católica. Contra la estafa de las pre-pagas y el negocio de las clínicas y sanatorios privados. Por un sistema nacional de salud público y universal, a cargo del Estado. Por una educación nacional única, estatal, gratuita y laica.',temas.EDUCACION, 9,0),
Propuesta('Defensa de la educación y salud públicas y gratuitas','Defensa de la educación y salud públicas y gratuitas. Basta de subsidio a la educación privada. Fuera la iglesia de la educación. Abajo la Ley de Educación Superior. Que el Estado deje de financiar a la Iglesia Católica. Contra la estafa de las pre-pagas y el negocio de las clínicas y sanatorios privados. Por un sistema nacional de salud público y universal, a cargo del Estado. Por una educación nacional única, estatal, gratuita y laica.',temas.SALUD, 9,0),
Propuesta('Por la provisión de medicamentos gratuitos a quienes lo necesitan','Nacionalización sin pago de los laboratorios que lucran con la salud del pueblo. Por la provisión de medicamentos gratuitos a quienes lo necesitan. Por la expulsión de la burocracia sindical de las obras sociales, y su control democrático por parte de comités de trabajadores elegidos en la base.',temas.SALUD, 9,0),
Propuesta('Eliminación del IVA y de los impuestos al consumo','Eliminación del IVA y de los impuestos al consumo. Impuestos progresivos a las grandes fortunas. Impuestos extraordinarios a los grandes capitalistas (banqueros, terratenientes y empresarios) para resolver las necesidades más acuciantes del pueblo trabajador. ',temas.ECONOMIA, 9,0),
Propuesta('Fuera la burocracia sindical patronal de los ferrocarriles','Fuera la burocracia sindical patronal de los ferrocarriles. Reestatización del sistema ferroviario bajo control y gestión de los trabajadores de todos los niveles. Juicio y castigo a los responsables de la masacre de Once.',temas.TRANSPORTE, 9,0),
Propuesta('Perpetua para todos los culpables del crimen de Mariano Ferreyra','Perpetua para todos los culpables del crimen de Mariano Ferreyra (UGOFE, Policía, Pedraza y su patota).',temas.SOCIEDAD, 9,0),
Propuesta('Fuera la burocracia de los sindicatos','Fuera la burocracia de los sindicatos. Por la independencia de los mismos del gobierno y el Estado. Abajo la Ley de Asociaciones Profesionales. Por la más plena democracia sindical. Personería gremial ya al nuevo sindicato del subte. Por el derecho de los trabajadores a organizarse, sin la ingerencia y el control estatal. Por elección de paritarios en asamblea. Apoyo al sindicalismo combativo y antiburocrático. ',temas.ECONOMIA, 9,0),
Propuesta('Fuera el FMI y la patota kirchnerista del INDEC','Fuera el FMI y la patota kirchnerista del INDEC. Restitución de todo el personal desplazado. Por un INDEC administrado por sus trabajadores y técnicos, independiente de cualquier gobierno patronal.',temas.ECONOMIA, 9,0),
Propuesta('Aparición con vida de Jorge Julio López','Aparición con vida de Jorge Julio López. Cárcel a los asesinos materiales y políticos de Carlos Fuentealba. Cárcel perpetua y común para todos los genocidas, a los responsables de los crímenes de la Triple A y a los asesinos del gatillo fácil. No a la baja de la edad de imputabilidad. Fuera la Gendarmería y policía de los barrios populares. Anulación de la ley “antiterrorista',temas.SOCIEDAD, 9,0),
Propuesta('Por el derecho al aborto legal, seguro y gratuito','Por el derecho al aborto legal, seguro y gratuito. Anticonceptivos para no abortar, aborto legal para no morir. Por los derechos de la mujer trabajadora. Por el desmantelamiento de las redes de trata. A igual trabajo, igual salario. Guarderías gratuitas en los lugares de trabajo y estudio. Por plena libertad para todas y todos de ejercer la elección de su sexualidad. Contra toda forma de opresión sexual. Abajo los edictos persecutorios y cualquier forma de opresión o discriminación contra gays, lesbianas, travestis, intersexuales y transexuales.',temas.DERECHOS_HUMANOS, 9,0),
Propuesta('Vivienda para los trabajadores','Vivienda para los trabajadores. Por un plan de viviendas populares y urbanización de las villas y asentamientos. Por impuestos progresivos a las viviendas ociosas de los especuladores inmobiliarios. No a la criminalización de los ocupantes del Indoamericano y de otras luchas por la tierra.',temas.PLANEAMIENTO_URBANO, 9,0),
Propuesta('Por un plan de obras públicas','Por un plan de obras públicas, saneamiento, prevención de inundaciones y cloacas bajo control de trabajadores y organizaciones barriales, empadronando y asegurando trabajo con convenio a los desocupados. Por la derogación de los códigos urbanos que sirven al capital financiero e inmobiliario. Por una planificación urbana debatida y dirigida por representantes de las organizaciones vecinales, populares y de trabajadores.',temas.PLANEAMIENTO_URBANO, 9,0),
Propuesta('Que todo legislador, funcionario estatal o juez gane lo mismo que un obrero especializado o un maestro','Que todo legislador, funcionario estatal o juez gane lo mismo que un obrero especializado o un maestro. Revocabilidad de todos los mandatos por los propios electores. Abolición del Senado y de la institución presidencial con poderes de monarca. Por una cámara única, con miembros elegidos utilizando el conjunto del país como distrito único.',temas.ECONOMIA, 9,0),
Propuesta('Que se ponga fin a los privilegios de los jueces','Que se ponga fin a los privilegios de los jueces, como la inmovilidad en sus cargos y las exenciones impositivas. Que todo juez gane lo mismo que un docente. Que cesen en sus cargos todos los jueces en funciones que juraron por el estatuto de la dictadura. No al Consejo de la magistratura y a al actual método de designación de los magistrados. Que los jueces sean elegidos por el voto popular. Que sus cargos puedan ser revocados por sus electores.',temas.SOCIEDAD, 9,0),
Propuesta('Por un gobierno de los trabajadores y el pueblo','Por un gobierno de los trabajadores y el pueblo impuesto por la movilización de los explotados y oprimidos.',temas.SOCIEDAD, 9,0),
Propuesta('Retiro inmediato de las tropas argentinas de Haití','Retiro inmediato de las tropas argentinas de Haití. Fuera ingleses y la OTAN de Malvinas. Contra el bloqueo y cualquier tipo de agresión imperialista contra Cuba. Por una política internacional de apoyo a la rebelión obrera y popular en todo el mundo, por la expulsión del imperialismo de todos los países, por la unidad socialista de América Latina, por el socialismo internacional',temas.INTERNACIONAL, 9,0),
Propuesta('Fuera el imperialismo de medio oriente','Fuera el imperialismo de medio oriente. Abajo la ocupación sionista de Palestina.',temas.INTERNACIONAL, 9,0),

];
}